version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dotnet-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      frontend-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
