#!/usr/bin/with-contenv bash

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

# permissions
echo "Setting permissions"
chown -R abc:abc \
	/app /data 

echo "Changing to /app folder"
cd /app || exit

echo "Starting alldebridclient"
exec \
  s6-setuidgid abc dotnet Adb.Client.Web.dll