#!/usr/bin/with-contenv bash

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo "UMASK_SET is deprecated; use UMASK instead."
  umask "${UMASK_SET}"
fi

echo "Starting AllDebrid Client"
cd /app || exit 1
exec s6-setuidgid abc dotnet AdbClient.Web.dll
