services:
  alldebrid-client:
    image: ghcr.io/krkn-dev/alldebrid-client:latest
    container_name: alldebrid-client
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ../data/downloads:/data/downloads
      - ../data/db:/data/db
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - "6500:6500"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:6500/health"]
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 10s
